### ISSUE TITLE
Use nginx for the webserver?

### ISSUE THREAD

**Issue by mikehostetler** [cogini/elixir-deploy-template#9]
Why not use nginx for the webserver vs. using `iptables` to route port 80 to 4000?

Was this intentional, or just trying to keep things simpler?

**Comment by reachfh** [comment]
It's intentional. Unless you need Nginx, e.g. to be a common front end which routes traffic to multiple back end applications, it's better to just have Phoenix listen directly.

Here is a full Nginx config and discussion of where it starts to fall down under load: https://www.cogini.com/blog/serving-your-phoenix-app-with-nginx/

**Comment by mikehostetler** [comment]
Interesting, thanks!
